export {default as dimsideris} from './dimsideris.png'
export {default as elena_m} from './elena_m.png'
export {default as iosif_darousis} from './iosif_darousis.png'
export {default as m_papagewrgiou} from './m_papagewrgiou.png'
export {default as olga_politi} from './olga_politi.png'
export {default as petros_kilamenakis} from './petros_kilamenakis.png'
export {default as stella_daviti} from './stella_daviti.png'
export {default as zoe_bah} from './zoe_bah.png'