export {default as elena} from './elena.png'
export {default as iosif} from './iosif.png'
export {default as olga} from './olga.png'
export {default as papagewrgiou} from './papagewrgiou.png'
export {default as petros} from './petros.png'
export {default as sideris} from './sideris.png'
export {default as stella} from './stella.png'
export {default as zoe} from './zoe.png'
