export {default as dryslope1} from './ALE_0520.webp'
export {default as dryslope2} from './ALE_0525.webp'
export {default as dryslope3} from './ALE_0529.webp'
export {default as dryslope4} from './ALE_0540.webp'
export {default as dryslope5} from './ALE_0629.webp'
export {default as dryslope6} from './ALE_5316.webp'
