const menu: Array<MenuItem> = [
  {
    name: 'Ελληνικός',
    category: 'Ροφημα',
    description: null,
    price: 2,
  },
  {
    name: 'Ελληνικός διπλός',
    category: 'Ροφημα',
    description: null,
    price: 2.5,
  },
  {
    name: 'Στιγμιαίος',
    category: 'Ροφημα',
    description: ['Κρύος', 'Ζεστός'],
    price: 3,
  },
  {
    name: 'Φίλτρου',
    category: 'Ροφημα',
    description: null,
    price: 3,
  },
  {
    name: 'Φίλτρου με καραμέλα',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Espresso',
    category: 'Ροφημα',
    description: null,
    price: 2.5,
  },
  {
    name: 'Espresso lungo',
    category: 'Ροφημα',
    description: null,
    price: 2.5,
  },
  {
    name: 'Espresso διπλός',
    category: 'Ροφημα',
    description: null,
    price: 3,
  },
  {
    name: 'Espresso Americano',
    category: 'Ροφημα',
    description: null,
    price: 3,
  },
  {
    name: 'Cappuccino',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Cappuccino διπλός',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Cappuccino με καραμέλα',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Freddo Espresso',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Freddo Cappuccino',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Freddo Cappuccino με καραμέλα',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Σοκολάτα',
    category: 'Ροφημα',
    description: ['Κρύα', 'Ζεστή'],
    price: 3.5,
  },
  {
    name: 'Milkshake',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Γρανίτα',
    category: 'Αναψυκτικο',
    description: null,
    price:3,
  },
  {
    name: 'Εμφιαλωμένο νερό',
    category: 'Αναψυκτικο',
    description: null,
    price: 0.5,
  },
  {
    name: 'Αναψυκτικο 330ml',
    category: 'Αναψυκτικο',
    description: [
      'Coca Cola', 
      'Sprite', 
      'Fanta',
      'Soda',
      'Tonic'
    ],
    price: 3,
  },
  {
    name: 'Χυμός Amita',
    category: 'Αναψυκτικο',
    description: [
      'Πορτοκάλι', 
      'Βύσσινο', 
      'Μπανάνα', 
      'Ροδάκινο', 
      'Ανάμικτος'
    ],
    price: 3,
  },
  {
    name: 'Χυμός Amita για παιδιά',
    category: 'Αναψυκτικο',
    description: ['Φράουλα', 'Μήλο'],
    price: 2,
  },
  {
    name: 'Τσάι Lipton',
    category: 'Αναψυκτικο',
    description: ['Λεμόνι', 'Ροδάκινο', 'Πράσινο'],
    price: 3.5,
  },
  {
    name: 'Χυμός Λεμονόδασος',
    category: 'Αναψυκτικο',
    description: [
      '100% Λεμόνι', 
      'Χυμός αγγούρι & αγαύη', 
      'Βυσσινάδα με χυμό λεμόνι',
      'Τζίντζερ & στέβια',
      'Ρόδι με χυμό λεμόνι',
      'Μαστίχα Χίου',
      'Φραουλάδα με χυμό λεμόνι',
    ],
    price: 4,
  },
  {
    name: 'Μαστιχόνερο',
    category: 'Αναψυκτικο',
    description: ['Ανθρακούχο', 'Λεμόνι'],
    price: 4,
  },
  {
    name: 'Perrier',
    category: 'Αναψυκτικο',
    description: null,
    price: 4,
  },
  {
    name: 'Pink Grapefruit',
    category: 'Αναψυκτικο',
    description: null,
    price: 4,
  },
  {
    name: 'Βεργίνα',
    category: 'Αλκοολουχο',
    description: null,
    price: 3.5,
  },
  {
    name: 'Heineken',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Heineken Zero',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Amstel',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Amstel Free',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Amstel Radler',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Sol',
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: 'Βαρέλι Ξανθιά',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Βαρέλι Weiss',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Μηλοκλέφτης',
    category: 'Αλκοολουχο',
    description: null,
    price: 4.5,
  },
  {
    name: 'Redbull',
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: 'Redbull Light',
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: "Gordon's Space",
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: 'Ατομικό Κρασί 187ml',
    category: 'Αλκοολουχο',
    description: [
      'Ημίγλυκο Λευκό/Κόκκινο',
      'Ξηρό Λευκό/Κόκκινο',
    ],
    price: 4.5,
  },
  {
    name: 'Ποτό Απλό',
    category: 'Αλκοολουχο',
    description: null,
    price: 6,
  },
  {
    name: 'Ποτό Special',
    category: 'Αλκοολουχο',
    description: null,
    price: 8,
  },
  {
    name: 'Mojito',
    category: 'Αλκοολουχο',
    description: [
      'Original', 
      'Μαστίχα', 
      'Φράουλα'
    ],
    price: 6,
  },
  {
    name: 'Caipirinha',
    category: 'Αλκοολουχο',
    description: [
      'Original', 
      'Ursus'
    ],
    price: 6,
  },
  {
    name: 'Negroni',
    category: 'Αλκοολουχο',
    description: null,
    price: 6,
  },
  {
    name: 'Daiquiri',
    category: 'Αλκοολουχο',
    description: null,
    price: 6,
  },
  {
    name: 'Τοστ',
    category: 'Φαγητο',
    description: null,
    price: 2,
  },
  {
    name: 'Ποπ Κορν',
    category: 'Φαγητο',
    description: null,
    price: 2,
  },
  {
    name: 'Βραστό Καλαμπόκι',
    category: 'Φαγητο',
    description: null,
    price: 2.5,
  },
  {
    name: 'Κριτσίνια Κοτόπουλο',
    category: 'Φαγητο',
    description: null,
    price: 4,
  },
  {
    name: 'Hot dog',
    category: 'Φαγητο',
    description: null,
    price: 2.5,
  },
  {
    name: 'Πατάτες μερίδα',
    category: 'Φαγητο',
    description: null,
    price: 2.5,
  },
  {
    name: 'Nachos',
    category: 'Φαγητο',
    description: null,
    price: 3,
  },
  {
    name: 'Churros',
    category: 'Φαγητο',
    description: null,
    price: 3,
  },
  {
    name: 'Τορτίγια Κοτόπουλο',
    category: 'Φαγητο',
    description: [
      'Κοτοσαλάτα',
      'Ντομάτα',
      'Μαρούλι',
      'Καλαμπόκι'
    ],
    price: 5,
  },
  {
    name: 'Yuppii Burger',
    category: 'Φαγητο',
    description: [
      'Πατάτες',
      'Ψωμί brioche',
      'Μπιφτέκι',
      'Μπέϊκον',
      'Ντομάτα',
      'Μαρούλι',
      'Σως μπάρμπεκιου',
      'Κεφαλοτύρι'
    ],
    price: 4.5,
  },
  {
    name: 'Yuppii Cheese Burger',
    category: 'Φαγητο',
    description: [
      'Πατάτες',
      'Ψωμί brioche',
      'Μπιφτέκι',
      'Αγγουρομαγιονέζα',
      'Τσένταρ',
      'Κέτσαπ'
    ],
    price: 4,
  },
  {
    name: 'Yuppii Chicken Burger',
    category: 'Φαγητο',
    description: [
      'Πατάτες',
      'Ψωμί brioche',
      'Κοτόπουλο πανέ',
      'Σως μουστάρδας',
      'Τσένταρ',
      'Μαρούλι'
    ],
    price: 5,
  },
  {
    name: 'Βιενέζικη Μπαγκέτα',
    category: 'Φαγητο',
    description: [
      'Φέτα',
      'Ελιές',
      'Ντομάτα',
      'Σως τυριού',
      'Ρίγανη'
    ],
    price: 4,
  },
  {
    name: 'Βιενέζικη Μπαγκέτα Κοτόπουλο',
    category: 'Φαγητο',
    description: [
      'Φιλέτο κοτόπουλο',
      'Μαγιονέζα',
      'Ντομάτα',
      'Μαρούλι',
      'Κεφαλοτύρι'
    ],
    price: 4,
  },
  {
    name: 'Club Sandwich',
    category: 'Φαγητο',
    description: null,
    price: 5.5,
  },
  {
    name: 'Chicken Club Sandwich',
    category: 'Φαγητο',
    description: null,
    price: 5.5,
  },
  {
    name: 'Yuppii Κοτομπουκιές',
    category: 'Φαγητο',
    description: null,
    price: 5.5,
  },
  {
    name: 'Yuppii Chickys',
    category: 'Φαγητο',
    description: null,
    price: 5,
  },
  {
    name: 'Ποικιλία Μπύρας',
    category: 'Φαγητο',
    description: null,
    price: 8,
  },
  {
    name: 'Πίτσα Μαργαρίτα',
    category: 'Φαγητο',
    description: [
      'Gouda',
      'Σάλτσα ντομάτας',
      'Βασιλικός',
      'Ντομάτα'
    ],
    price: 7,
  },
  {
    name: 'Πίτσα Special',
    category: 'Φαγητο',
    description: [
      'Gouda',
      'Μοτσαρέλα',
      'Μπέϊκον',
      'Πράσινη πιπεριά',
      'Μανιτάρια',
      'Σάλτσα ντομάτας',
    ],
    price: 7.5,
  },
  {
    name: 'Πίτσα 4 Τυριά',
    category: 'Φαγητο',
    description: [
      'Τσένταρ',
      'Gouda',
      'Gouda Καπνιστό',
      'Μοτσαρέλα',
      'Σάλτσα ντομάτας',
    ],
    price: 7.5,
  },
  {
    name: 'Πίτσα Ελληνική',
    category: 'Φαγητο',
    description: [
      'Φέτα',
      'Ελιές',
      'Ντομάτα',
      'Gouda',
      'Ρίγανη',
      'Κρεμμύδι',
      'Σάλτσα ντομάτας',
    ],
    price: 7.5,
  },
  {
    name: 'Πίτσα Προσούτο',
    category: 'Φαγητο',
    description: [
      'Προσούτο',
      'Μοτσαρέλα',
      'Τσένταρ',
      'Ρόκα',
      'Σάλτσα ντομάτας',
    ],
    price: 7.5,
  },
  {
    name: 'Πίτσα Vegetarian',
    category: 'Φαγητο',
    description: [
      'Νηστίσιμο κασέρι',
      'Καλαμπόκι',
      'Πράσινη πιπεριά',
      'Μανιτάρια',
      'Ελιές',
    ],
    price: 7.5,
  },
  {
    name: 'Πίτσα Κοτόπουλο',
    category: 'Φαγητο',
    description: [
      'Κοτόπουλο',
      'Τυρί κρέμα',
      'Βασιλικός',
      'Καλαμπόκι',
      'Σως μουστάρδας',
    ],
    price: 7.5,
  },
  {
    name: 'Κρέπα Classic',
    category: 'Φαγητο',
    description: [
      'Γκούντα',
      'Καπνιστή γαλοπούλα',
    ],
    price: 2.5,
  },
  {
    name: 'Κρέπα Light',
    category: 'Φαγητο',
    description: [
      'Καπνιστή γαλοπούλα',
      'Καλαμπόκι',
      'Τυρί χαμηλών λιπαρών',
      'Ντομάτα'
    ],
    price: 3.5,
  },
  {
    name: 'Κρέπα Ελληνική',
    category: 'Φαγητο',
    description: [
      'Φέτα',
      'Ντομάτα',
      'Ελιές',
      'Πιπεριά',
      'Σως γιαουρτιού'
    ],
    price: 4,
  },
  {
    name: 'Κρέπα Καπνιστή',
    category: 'Φαγητο',
    description: [
      'Καπνιστή μπριζόλα',
      'Ντομάτα',
      'Τυροκαυτερή',
      'Κεφαλοτύρι'
    ],
    price: 4,
  },
  {
    name: 'Κρέπα Philadelphia',
    category: 'Φαγητο',
    description: [
      'Γκούντα',
      'Αυγό',
      'Ντομάτα',
      'Philadelphia'
    ],
    price: 4,
  },
  {
    name: 'Κρέπα Mediterranean',
    category: 'Φαγητο',
    description: [
      'Φιλέτο κοτόπουλο',
      'Τσένταρ',
      'Καλαμπόκι',
      'Ντομάτα',
      'Τυροσαλάτα'
    ],
    price: 4.5,
  },
  {
    name: 'Κρέπα Bueno',
    category: 'Φαγητο',
    description: [
      'Πραλίνα bueno',
      'Μπισκότο'
    ],
    price: 3,
  },
  {
    name: 'Κρέπα Double Dream',
    category: 'Φαγητο',
    description: [
      'Πραλίνα φράουλα',
      'Μπανάνα',
      'Μπισκότο',
      'Τρούφα'
    ],
    price: 4.5,
  },
  {
    name: 'Κρέπα Energy',
    category: 'Φαγητο',
    description: [
      'Nutella',
      'Μπανάνα',
      'Καρύδι',
      'Super food'
    ],
    price: 4.5,
  },
  {
    name: 'Κρέπα Σοκολατομάνια',
    category: 'Φαγητο',
    description: [
      'Πραλίνα σοκολάτα',
      'Oreo',
      'Smarties'
    ],
    price: 5,
  },
  {
    name: 'Κρέπα On Ice',
    category: 'Φαγητο',
    description: [
      'Παγωτό',
      'Πραλίνα σοκολάτα',
      'Oreo'
    ],
    price: 5,
  },
]

const menuEnglish: Array<MenuItem> = [
  {
    name: 'Greek Coffee',
    category: 'Ροφημα',
    description: null,
    price: 2,
  },
  {
    name: 'Double Greek Coffee',
    category: 'Ροφημα',
    description: null,
    price: 2.5,
  },
  {
    name: 'Instant Coffee',
    category: 'Ροφημα',
    description: ['Cold', 'Hot'],
    price: 3,
  },
  {
    name: 'Filtered Coffee',
    category: 'Ροφημα',
    description: null,
    price: 3,
  },
  {
    name: 'Filtered Coffee with Caramel',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Espresso',
    category: 'Ροφημα',
    description: null,
    price: 2.5,
  },
  {
    name: 'Espresso Lungo',
    category: 'Ροφημα',
    description: null,
    price: 2.5,
  },
  {
    name: 'Double Espresso',
    category: 'Ροφημα',
    description: null,
    price: 3,
  },
  {
    name: 'Espresso Americano',
    category: 'Ροφημα',
    description: null,
    price: 3,
  },
  {
    name: 'Cappuccino',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Double Cappuccino',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Cappuccino with Caramel',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Freddo Espresso',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Freddo Cappuccino',
    category: 'Ροφημα',
    description: null,
    price: 3.5,
  },
  {
    name: 'Freddo Cappuccino with Caramel',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Chocolate',
    category: 'Ροφημα',
    description: ['Cold', 'Hot'],
    price: 3.5,
  },
  {
    name: 'Milkshake',
    category: 'Ροφημα',
    description: null,
    price: 4,
  },
  {
    name: 'Slush',
    category: 'Αναψυκτικο',
    description: null,
    price: 3,
  },
  {
    name: 'Table Water',
    category: 'Αναψυκτικο',
    description: null,
    price: 0.5,
  },
  {
    name: 'Beverage 330ml',
    category: 'Αναψυκτικο',
    description: [
      'Coca-Cola',
      'Sprite',
      'Fanta',
      'Soda',
      'Tonic',
    ],
    price: 3,
  },
  {
    name: 'Amita Juice',
    category: 'Αναψυκτικο',
    description: [
      'Orange',
      'Sour Cherry',
      'Banana',
      'Peach',
      'Mixed',
    ],
    price: 3,
  },
  {
    name: 'Amita Kids Juice',
    category: 'Αναψυκτικο',
    description: ['Strawberry', 'Apple'],
    price: 2,
  },
  {
    name: 'Lipton Iced Tea',
    category: 'Αναψυκτικο',
    description: ['Lemon', 'Peach', 'Green'],
    price: 3.5,
  },
  {
    name: 'Lemonodasos Juice',
    category: 'Αναψυκτικο',
    description: [
      '100% Lemon',
      'Cucumber & Mint Juice',
      'Sour Cherry with Lemon Juice',
      'Ginger & Stevia',
      'Pomegranate with Lemon Juice',
      'Chios Mastic',
      'Strawberry with Lemon Juice',
    ],
    price: 4,
  },
  {
    name: 'Mastiqua',
    category: 'Αναψυκτικο',
    description: ['Sparkling', 'Lemon'],
    price: 4,
  },
  {
    name: 'Perrier',
    category: 'Αναψυκτικο',
    description: null,
    price: 4,
  },
  {
    name: 'Pink Grapefruit',
    category: 'Αναψυκτικο',
    description: null,
    price: 4,
  },
  {
    name: 'Vergina',
    category: 'Αλκοολουχο',
    description: null,
    price: 3.5,
  },
  {
    name: 'Heineken',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Heineken Zero',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Amstel',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Amstel Free',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Amstel Radler',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Sol',
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: 'Blonde Draft Beer',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Weiss Draft Beer',
    category: 'Αλκοολουχο',
    description: null,
    price: 4,
  },
  {
    name: 'Apple Cider',
    category: 'Αλκοολουχο',
    description: null,
    price: 4.5,
  },
  {
    name: 'Red Bull',
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: 'Red Bull Light',
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: "Gordon's Space",
    category: 'Αλκοολουχο',
    description: null,
    price: 5,
  },
  {
    name: 'Mini Wine 187ml',
    category: 'Αλκοολουχο',
    description: [
      'Semi-sweet White/Red',
      'Dry White/Red',
    ],
    price: 4.5,
  },
  {
    name: 'Regular Drink',
    category: 'Αλκοολουχο',
    description: null,
    price: 6,
  },
  {
    name: 'Special Drink',
    category: 'Αλκοολουχο',
    description: null,
    price: 8,
  },
  {
    name: 'Mojito',
    category: 'Αλκοολουχο',
    description: [
      'Original', 
      'Mastic', 
      'Strawberry'
    ],
    price: 6,
  },
  {
    name: 'Caipirinha',
    category: 'Αλκοολουχο',
    description: [
      'Original', 
      'Ursus'
    ],
    price: 6,
  },
  {
    name: 'Negroni',
    category: 'Αλκοολουχο',
    description: null,
    price: 6,
  },
  {
    name: 'Daiquiri',
    category: 'Αλκοολουχο',
    description: null,
    price: 6,
  },
  {
    name: 'Toast',
    category: 'Φαγητο',
    description: null,
    price: 2,
  },
  {
    name: 'Popcorn',
    category: 'Φαγητο',
    description: null,
    price: 2,
  },
  {
    name: 'Boiled Corn',
    category: 'Φαγητο',
    description: null,
    price: 2.5,
  },
  {
    name: 'Chicken Breadsticks',
    category: 'Φαγητο',
    description: null,
    price: 4,
  },
  {
    name: 'Hot Dog',
    category: 'Φαγητο',
    description: null,
    price: 2.5,
  },
  {
    name: 'Fried Fries',
    category: 'Φαγητο',
    description: null,
    price: 2.5,
  },
  {
    name: 'Nachos',
    category: 'Φαγητο',
    description: null,
    price: 3,
  },
  {
    name: 'Churros',
    category: 'Φαγητο',
    description: null,
    price: 3,
  },
  {
    name: 'Chicken Tortilla',
    category: 'Φαγητο',
    description: [
      'Chicken Salad',
      'Tomato',
      'Lettuce',
      'Corn',
    ],
    price: 5,
  },
  {
    name: 'Yuppii Burger',
    category: 'Φαγητο',
    description: [
      'Fries',
      'Brioche Bun',
      'Beef Patty',
      'Bacon',
      'Tomato',
      'Lettuce',
      'Barbecue Sauce',
      'Cheese',
    ],
    price: 4.5,
  },
  {
    name: 'Yuppii Cheese Burger',
    category: 'Φαγητο',
    description: [
      'Fries',
      'Brioche Bun',
      'Beef Patty',
      'Mayonnaise',
      'Cheddar',
      'Ketchup',
    ],
    price: 4,
  },
  {
    name: 'Yuppii Chicken Burger',
    category: 'Φαγητο',
    description: [
      'Fries',
      'Brioche Bun',
      'Breaded Chicken',
      'Mustard Sauce',
      'Ketchup',
      'Lettuce',
    ],
    price: 5,
  },
  {
    name: 'Viennese Baguette',
    category: 'Φαγητο',
    description: [
      'Greek feta',
      'Olives',
      'Tomato',
      'Cheese Sauce',
      'Oregano',
    ],
    price: 4,
  },
  {
    name: 'Chicken Viennese Baguette',
    category: 'Φαγητο',
    description: [
      'Chicken Fillet',
      'Mayonnaise',
      'Tomato',
      'Lettuce',
      'Cheese',
    ],
    price: 4,
  },
  {
    name: 'Club Sandwich',
    category: 'Φαγητο',
    description: null,
    price: 5.5,
  },
  {
    name: 'Chicken Club Sandwich',
    category: 'Φαγητο',
    description: null,
    price: 5.5,
  },
  {
    name: 'Yuppii Chicken Nuggets',
    category: 'Φαγητο',
    description: null,
    price: 5.5,
  },
  {
    name: 'Yuppii Chickys',
    category: 'Φαγητο',
    description: null,
    price: 5,
  },
  {
    name: 'Cold Cuts variety',
    category: 'Φαγητο',
    description: null,
    price: 8,
  },
  {
    name: 'Margherita Pizza',
    category: 'Φαγητο',
    description: [
      'Gouda',
      'Tomato Sauce',
      'Basil',
      'Tomato',
    ],
    price: 7,
  },
  {
    name: 'Special Pizza',
    category: 'Φαγητο',
    description: [
      'Gouda',
      'Mozzarella',
      'Bacon',
      'Green Pepper',
      'Mushrooms',
      'Tomato Sauce',
    ],
    price: 7.5,
  },
  {
    name: 'Four Cheese Pizza',
    category: 'Φαγητο',
    description: [
      'Cheddar',
      'Gouda',
      'Smoked Gouda',
      'Mozzarella',
      'Tomato Sauce',
    ],
    price: 7.5,
  },
  {
    name: 'Greek Pizza',
    category: 'Φαγητο',
    description: [
      'Greek feta',
      'Olives',
      'Tomato',
      'Gouda',
      'Oregano',
      'Onion',
      'Tomato Sauce',
    ],
    price: 7.5,
  },
  {
    name: 'Prosciutto Pizza',
    category: 'Φαγητο',
    description: [
      'Prosciutto',
      'Mozzarella',
      'Cheddar',
      'Arugula',
      'Tomato Sauce',
    ],
    price: 7.5,
  },
  {
    name: 'Vegetarian Pizza',
    category: 'Φαγητο',
    description: [
      'Fasting Cheese',
      'Corn',
      'Green Pepper',
      'Mushrooms',
      'Olives',
    ],
    price: 7.5,
  },
  {
    name: 'Chicken Pizza',
    category: 'Φαγητο',
    description: [
      'Chicken',
      'Cream Cheese',
      'Basil',
      'Corn',
      'Mustard Sauce',
    ],
    price: 7.5,
  },
  {
    name: 'Classic Crepe',
    category: 'Φαγητο',
    description: [
      'Gouda',
      'Smoked Turkey',
    ],
    price: 2.5,
  },
  {
    name: 'Light Crepe',
    category: 'Φαγητο',
    description: [
      'Smoked Turkey',
      'Corn',
      'Low-Fat Cheese',
      'Tomato',
    ],
    price: 3.5,
  },
  {
    name: 'Greek Crepe',
    category: 'Φαγητο',
    description: [
      'Greek feta',
      'Tomato',
      'Olives',
      'Bell Pepper',
      'Yogurt Sauce',
    ],
    price: 4,
  },
  {
    name: 'Smoked Crepe',
    category: 'Φαγητο',
    description: [
      'Smoked Beef',
      'Tomato',
      'Spicy Cheese Spread',
      'Cheese',
    ],
    price: 4,
  },
  {
    name: 'Philadelphia Crepe',
    category: 'Φαγητο',
    description: [
      'Gouda',
      'Egg',
      'Tomato',
      'Philadelphia Cream Cheese',
    ],
    price: 4,
  },
  {
    name: 'Mediterranean Crepe',
    category: 'Φαγητο',
    description: [
      'Chicken fillet',
      'Tzatziki',
      'Corn',
      'Tomato',
      'Cheese salad',
    ],
    price: 4.5,
  },
  {
    name: 'Bueno Crepe',
    category: 'Φαγητο',
    description: [
      'Bueno Praline',
      'Biscuit',
    ],
    price: 3,
  },
  {
    name: 'Double Dream Crepe',
    category: 'Φαγητο',
    description: [
      'Strawberry Praline',
      'Banana',
      'Biscuit',
      'Truffle',
    ],
    price: 4.5,
  },
  {
    name: 'Energy Crepe',
    category: 'Φαγητο',
    description: [
      'Nutella',
      'Banana',
      'Walnut',
      'Super Food',
    ],
    price: 4.5,
  },
  {
    name: 'Chocolamania Crepe',
    category: 'Φαγητο',
    description: [
      'Chocolate Praline',
      'Oreo',
      'Smarties',
    ],
    price: 5,
  },
  {
    name: 'On Ice Crepe',
    category: 'Φαγητο',
    description: [
      'Ice Cream',
      'Chocolate Praline',
      'Oreo',
    ],
    price: 5,
  },
]

export {menu}