export {default as bumperCars1thumb} from './ALE_0654_thumb.webp'
export {default as bumperCars2thumb} from './ALE_0659_thumb.webp'
export {default as bumperCars3thumb} from './ALE_0663_thumb.webp'
export {default as bumperCars4thumb} from './ALE_5184_thumb.webp'
export {default as bumperCars5thumb} from './ALE_5368_thumb.webp'
export {default as bumperCars6thumb} from './ALE_5483_thumb.webp'