export {default as cranes1} from './ALE_0602.webp'
export {default as cranes2} from './ALE_0619.webp'
export {default as cranes3} from './ALE_0776.webp'
export {default as cranes4} from './ALE_0809.webp'
export {default as cranes5} from './ALE_5217.webp'
export {default as cranes6} from './ALE_5225.webp'
export * from './thumbs'