export {default as trampoline1} from './ALE_0643.webp'
export {default as trampoline2} from './ALE_0898.webp'
export {default as trampoline3} from './ALE_0934.webp'
export {default as trampoline4} from './AL_07496.webp'
export {default as trampoline5} from './AL_07497.webp'
export {default as trampoline6} from './AL_07503.webp'
