#!/bin/bash

echo "🚀 Checking before pushing..."

echo ""
echo "⏳ Generating project types..."
pnpm next typegen

echo ""
echo "⏳ Type-checking..."
pnpm typecheck || { echo ""; echo "❌ Type errors. Push aborted."; exit 1; }

echo ""
echo "⏳ Linting..."
pnpm lint || { echo ""; echo "❌ Lint errors. Push aborted."; exit 1; }

echo ""
echo "✅ All checks passed. Pushing..."
echo ""
